name: deepscribe
channels:
  - anaconda
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pillow
  - pip
  - tensorflow-gpu=2.1
  - tqdm
  - scikit-image
  - scikit-learn
  - nb_conda
  - opencv
  - freetype
  - h5py==2.10
  - luigi
  - imbalanced-learn
  - pip:
      - git+https://github.com/autonomio/talos@1.0
      - wandb